version: '3.9'
services:
  commercecashflow.api:
    build:
      context: .
      dockerfile: src/CommerceCashFlow.Api/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - commercecashflow.db
      - commercecashflow.redis
    volumes:
      - ./src/CommerceCashFlow.Api:/app
  
  commercecashflow.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - dbdata:/var/opt/mssql

  commercecashflow.redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

volumes:
  dbdata:
  redisdata:
