version: '3.9'
services:
  commercecashflow.api:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - 5000:80
    depends_on:
      # - commercecashflow.redis
      commercecashflow.db:
        condition: service_healthy
    command: ["dotnet", "ef", "database update"]

  commercecashflow.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - dbdata:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  commercecashflow.redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

volumes:
  dbdata:
  redisdata:
